### PR TITLE
ProcControl and SymtabAPI support for ppcle64 platform

### PR DESCRIPTION
**Pull request by mcfadden8**
1) Cmake support for PPC64LE builds
2) Added ABI version and Endianness interface to SymReader and SymtabAPI
3) Added PPC64LE support for ProcControl and Symtab

**Note**: As previously discussed, I had to remove the 'extern template' lines from ast.C and dynProcess.C in order to build successfully on ppc64le platform (and ppc64).

### CODE REVIEW

**Comment by wrwilliams** [comment]
What's the test suite status on ppc64 and ppc64/le?

**Comment by mcfadden8** [comment]
I was able to successfully run ./runTests -proccontrol and ./runTests -symtab on both ppc64 and ppc64/le.

I did not try the other tests since I was only focusing on changes to those two interfaces and implementations.

Marty

**Comment by wrwilliams** [comment]
x86 has no new failures as a result of this. If you can check the state of ppc64 big-endian dyninst tests, that would be great, but I'm pretty sure you can treat that as "report issues and move on".
Main github presence is moving to dyninst/dyninst, but I can do the merge shuffle for this one if you like.

**Comment by mcfadden8** [comment]
./runTests -dyninst fails very quickly on the PPC64 big endian machine even running against the master branch sans my changes:

test_pt_ls (create) FAILED (Running Test)
test2_1 PASSED
test2_2 PASSED
test_pt_ls (rewriter) FAILED (Running Test)

Then it seems to hang.

**Comment by mcfadden8** [comment]
This pull request is being closed here and will be reopened at dyninst/dyninst

**Pull request closed without merging**
